import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider"
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn("flex flex-col min-h-screen", inter.className)}>
                <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
                    <Navbar />
                  <main className="flex-grow m-5">
                    {children}
          </main>
          <Footer />
        </ThemeProvider>
            </body>
        </html>
    );
}
