FROM node:20
WORKDIR /usr/src/app/frontend
EXPOSE 3000

COPY frontend /usr/src/app/frontend
COPY .env.production /usr/src/app/frontend/.env.production
RUN npm i

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/bin/sh", "/docker-entrypoint.sh"]