FROM node:20
WORKDIR /usr/src/app
COPY backend /usr/src/app/backend
COPY .env /usr/src/app/backend/.env
WORKDIR /usr/src/app/backend/
RUN npm install
RUN NODE_ENV=production npm run build
EXPOSE 1337
CMD ["npm", "run", "start"]
