version: "3.3"
services:
    backend:
        restart: unless-stopped
        volumes:
            - type: bind
              source: /var/data/
              target: /var/data/
            - type: bind
              source: /var/data/russemarkeduploads
              target: /usr/src/app/backend/public/uploads
        build:
            context: .
            dockerfile: Dockerfile-backend
        image: backend:outreach
        ports:
            - "8080:8080"
            
    frontend:
        depends_on:
            - backend
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile-frontend
        image: frontend:outreach
        ports:
            - "3000:3000"
