name: Server auto deploy
on:
  push:
    branches: ["main", "95-autoredeploy-on-main-change"]

jobs:
  docker-build:
    strategy:
      matrix:
        node-version: [20.x]
    defaults:
      run:
        env:
          HOST: ${{vars.HOST}}
          PORT: ${{vars.PORT}}
          DATABASE_CLIENT: ${{vars.DATABASE_CLIENT}}
          DATABASE_FILENAME: ${{vars.DATABASE_FILENAME}}
          ADMIN_JWT_SECRET: ${{secrets.ADMIN_JWT_SECRET}}
          API_TOKEN_SALT: ${{secrets.API_TOKEN_SALT}}
          APP_KEYS: ${{secrets.APP_KEYS}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          TRANSFER_TOKEN_SALT: ${{secrets.TRANSFER_TOKEN_SALT}}
          HOST_URL: ${{vars.HOST_URL}}

    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: sudo docker-compose build
      - run: sudo docker-compose up
